source "https://rubygems.org"


gem "sinatra"
gem "mysql2"
gem "mysql2-cs-bind"
gem "erubis"
gem "unicorn"
gem 'pry-byebug'
gem "redis", ">= 3.2.0", :require => ["redis", "redis/connection/hiredis"]
gem 'hiredis'
